[package]
name = "galadriel"
description = """Experiments in using rust and tokio-core to build networking tools"""
version = "0.0.1"
authors = [
  "Steve Jenson <stevej@buoyant.io>",
  "Oliver Gould <ver@buoyant.io>"
]
readme = "README.md"
license = "Apache-2.0"

[profile.release]
debug = true

[dependencies]
env_logger = "0.3"
futures = "0.1.9"
getopts = "0.2"
hyper = "0.10"
log = "0.3"
rand = "0.3"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
tokio-core = "0.1.4"
url = "1.4"
