[package]
name = "linkerd_tcp"
description = "A native TCP proxy for the linkerd service mesh"
version = "0.0.1"
authors = [
  "Steve Jenson <stevej@buoyant.io>",
  "Oliver Gould <ver@buoyant.io>"
]
readme = "README.md"
license = "Apache-2.0"

[profile.release]
debug = true

[dependencies]
clap = "2.20"
env_logger = "0.3"
futures = "0.1.9"
hyper = "0.10"
log = "0.3"
rand = "0.3"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
tokio-core = "0.1.4"
url = "1.4"
